### PR TITLE
Bump ethereum-types.

### PR DESCRIPTION
**Pull request by tomusdrw**

### CODE REVIEW

**Comment by barabadzhi** [comment]
Any news on this one? 🙂 
Blockers? 🛑

**Review by 0racl3z — COMMENTED** [review]
tests seem to have significant failure checks

**Comment by nlordell** [comment]
This has also been fixed in #215 /cc @vkgnosis

**Comment by vkgnosis** [comment]
Still need to make a release with it, but yes has been included.

**Review by 0racl3z — COMMENTED** [review]
=]

**Pull request closed without merging**
