### PR TITLE
avoid OOM on decoding corrupted array encodings

### PR DESCRIPTION
**Pull request by f0rki**
~~Currently ethabi can crash when parsing corrupted input data containing an array. This is due to an out-of-memory error when allocating a huge vector upfront. This can be easily avoided by checking whether the array length is possible for the given input before allocating the vector.~~

Not relevant anymore, but maybe the testcase I wrote is?

### CODE REVIEW

**Comment by f0rki** [comment]
my original PR doesn't seem relevant anymore. The testcase I added is now passing with the changes from v14. Maybe you'd like to add this testcase?

**Review by vkgnosis — APPROVED** [review]
The test case looks useful to me, thanks.

**Review by nlordell — APPROVED** [review]

**Comment by f0rki** [comment]
I pushed another fix (and a testcase) to this branch. There was a bounds check missing during decoding of dynamic tuples.

**Review by nlordell — APPROVED** [review]
Excellent!

**Pull request merged**
