### PR TITLE
Decode function, which fails, if some data left

### PR DESCRIPTION
**Pull request by leviska**
Right now `decode` will return ok, even if some input data is left. 
I'm writing a decoder, which tries to decode the tx input and logs not knowing exact signature, so it tries several signatures and picks whatever decodes successfully. But current implementation is wrong in this context: it can return "Ok", even if the data is not fully corresponds to the types provided

I suggest adding some function, which will also check, that it decodes everything, or returns error, because implementing it requires implementation details (knowing offset). Also I need to decode logs, so I've added additional implementation there too, and if I missed some other decodes, I will happily add other functions too

Current implementation is just the easiest way I thought this could be done, but I'm open for review and will fix it if you have a better idea. Naming is for debate too

### CODE REVIEW

**Comment by vkgnosis** [comment]
The change makes sense to me but we should probably do it in a backward compatible way. I'd keep the existing public functions as they are now and add new functions with the extra check.

**Comment by leviska** [comment]
I've added some basic tests and left the original functions as is

**Comment by vkgnosis** [comment]
One more nitpick. Sorry if I didn't make that clear in the previous comment. We should refactor out the common (copy pasted) parts between the base function and the _whole addition. What I meant before was that the behavior of the base function shouldn't change. We *can* change the implementation. Maybe the base function can call _whole internally or we need a third function that can be called by both.

**Comment by leviska** [comment]
that's what I did in the first attempt, so I didn't quite get what you're were asking for 😅

isn't the first version what you suggesting? 
we make `decode_offset` (private function), and call it from `decode` and `decode_whole`, and similar with events.

I tried to use errors, but then I'll need to add another error in the enum and that's probably not the most backward compatible way(?)

image

**Comment by vkgnosis** [comment]
You're right. I must have not paid attention when I read the first commit and thought it changed the behavior of the existing function. Just looked at the commit again and it looks fine.

**Comment by leviska** [comment]
No problem :) 

I've returned the old version

**Review by vkgnosis — APPROVED** [review]

**Pull request merged**
