### PR TITLE
feat: add Serialize trait to Token, Log and LogParams

### LINKED ISSUE #268: Add Serialize to Logs
This change is required in order to be able to Serialize events into json as per https://github.com/foundry-rs/foundry/issues/1432.

### PR DESCRIPTION
**Pull request by Genysys**
This PR closes #268

### CODE REVIEW

**Review by vkgnosis — COMMENTED** [review]
Makes sense to me. Looking at other code that uses serde I believe this should be feature gated behind the full-serde feature.

**Comment by Genysys** [comment]
Thanks for coming back quickly on this @vkgnosis . Can you please link an example of codebase that uses serde as such so I can amend the PR

**Comment by nlordell** [comment]
For example: https://github.com/rust-ethereum/ethabi/blob/451d029c69a1fce7c4d57cc117e985a31dc53627/ethabi/src/event.rs#L25

**Review by vkgnosis — COMMENTED** [review]
The `use serde::{Deserialize, Serialize};` lines also have to be feature gated.

**Review by vkgnosis — APPROVED** [review]

**Pull request merged**
